### ISSUE TITLE
Backported django.core.urlresolvers from django 1.10 necessary?

### ISSUE THREAD

**Issue by baerbock** [opensemanticsearch/open-semantic-search-apps#56]
I've installed your great tool collection from source with _ArchLinux_.

When I now run e.g. `python /var/lib/opensemanticsearch/manage.py collectstatic --noinput` from the postinstall scripts I'm getting:
`ModuleNotFoundError: No module named 'django.core.urlresolvers'`

Is opensemanticsearch meant to work with Django 1? Or is it necessary to backport (copy) django.core.urlresolvers from django 1.10?

**Comment by chazanov** [comment]
@Mandalka I'm also interested in this and could help with porting. But first I would like to get confirmation: Is _OSS_ Django 1 or Django 2 based?

**Comment by Mandalka** [comment]
OS dependencies :-/

Since based mainly running on Debian stable (next migrating of OSS to new Debian 10) it is/will be next
Django 1.11: https://packages.debian.org/buster/python3-django

Django 2 is available yet in Debian unstable (Sid):
https://packages.debian.org/sid/python3-django

Maybe soon there will be a backport for Debian stable, but not sure if running OSS on Debian stable with having backports as dependencies is good idea. :-/

**Comment by chazanov** [comment]
@chazanov Besides all Debian issues – do you know whether _open-semantic-search-apps_ would run with Django2 ? I'm suspecting not because of the above _'django.core.urlresolvers'_ issue.

**Comment by Mandalka** [comment]
I'll have a look (since some day it will come/will be needed), but maybe in some weeks, since other issues more important until then and not urgent using new Debian stable (which i have to migrate some things / VMs on).

I hope it's not too much to migrate/heavy changes, if not maybe possible to manage a parallel branch "Django 2" (can send yo an invitation for the Repo) and let master base on Django 1 for Debian stable.

**Comment by Mandalka** [comment]
Thanks a PR the git repository branch "master" is Django 2 since some weeks, the new branch "django1" is Django 1
