### ISSUE TITLE
missing search_entity subdirectory in src?

### ISSUE THREAD

**Issue by NetwarSystem** [opensemanticsearch/open-semantic-search-apps#59]
I built the entire open-semantic-search.deb by hand, then unpacked it. These are the directories in that deb.

drwxr-xr-x 5 nealr nealr  11 Jul 26 16:18 annotate  
drwxr-xr-x 2 nealr nealr   6 Jul 26 16:18 api  
drwxr-xr-x 5 nealr nealr  11 Jul 26 16:18 crawler  
drwxr-xr-x 5 nealr nealr  12 Jul 26 16:18 csv_manager  
drwxr-xr-x 4 nealr nealr  10 Jul 26 16:18 datasources  
drwxr-xr-x 2 nealr nealr   6 Jul 26 17:42 entity_rest_api  
drwxr-xr-x 5 nealr nealr  11 Jul 26 16:18 files  
drwxr-xr-x 5 nealr nealr  11 Jul 26 16:18 hypothesis  
-rw-r--r-- 1 nealr nealr 261 Jul 26 16:18 manage.py  
drwxr-xr-x 4 nealr nealr  10 Jul 26 16:18 morphology  
drwxr-xr-x 6 nealr nealr  13 Jul 26 16:18 ontologies  
drwxr-xr-x 2 nealr nealr   6 Jul 26 16:18 opensemanticsearch  
drwxr-xr-x 4 nealr nealr  10 Jul 26 16:18 querytagger  
drwxr-xr-x 5 nealr nealr  11 Jul 26 16:18 rss_manager  
drwxr-xr-x 4 nealr nealr  10 Jul 26 16:18 search_list  
drwxr-xr-x 5 nealr nealr  10 Jul 26 16:18 setup  
drwxr-xr-x 5 nealr nealr  11 Jul 26 16:18 thesaurus  
drwxr-xr-x 4 nealr nealr   8 Jul 26 17:48 visual_graph_explorer 

When I unpacked the official download from the website, this is what I find:

drwxr-xr-x 5 nealr nealr  11 Mar 22 10:31 annotate  
drwxr-xr-x 2 nealr nealr   6 Mar 22 10:31 api  
drwxr-xr-x 5 nealr nealr  11 Mar 22 10:31 crawler  
drwxr-xr-x 5 nealr nealr  12 Mar 22 10:31 csv_manager  
drwxr-xr-x 4 nealr nealr  10 Mar 22 10:31 datasources  
drwxr-xr-x 2 nealr nealr   6 Apr 23  2018 entity_rest_api  
drwxr-xr-x 5 nealr nealr  11 Mar 22 10:31 files  
drwxr-xr-x 5 nealr nealr  11 Mar 22 10:31 hypothesis  
-rw-r--r-- 1 nealr nealr 261 Mar 22 10:31 manage.py  
drwxr-xr-x 4 nealr nealr  10 Mar 22 10:31 morphology  
drwxr-xr-x 6 nealr nealr  13 Jun 16 02:21 ontologies  
drwxr-xr-x 2 nealr nealr   6 Mar 22 10:56 opensemanticsearch  
drwxr-xr-x 4 nealr nealr  10 Mar 22 10:31 querytagger  
drwxr-xr-x 5 nealr nealr  11 Mar 22 10:31 rss_manager  
**drwxr-xr-x 4 nealr nealr   8 Oct  3  2018 search_entity**  
drwxr-xr-x 4 nealr nealr  10 Mar 22 10:31 search_list  
drwxr-xr-x 5 nealr nealr  10 Jul 14 12:26 setup  
drwxr-xr-x 5 nealr nealr  11 Mar 22 10:31 thesaurus  
drwxr-xr-x 4 nealr nealr   8 Jul 19 11:26 visual_graph_explorer  

If I just rsync /var/lib/opensemanticsearch from the directory from the official deb, the system I built can be coaxed to run.

There is also a /var/lib/opensemanticsearch/static directory - seems to be related to cytoscape.js?? That must be rsync'd as well.

**Comment by Mandalka** [comment]
The app search_entity is not yet ready, but i uploaded it, so no error occurs if building from source.

**Comment by Mandalka** [comment]
Cytoscape dependencies since some time are defined in git repository open-semantic-search in /src ...

This (newer) part from build-deb copies them to final destination:

mkdir ${BUILDDIR}/var/lib/opensemanticsearch/visual_graph_explorer/static/
cp -a src/cytoscape.js/dist/* ${BUILDDIR}/var/lib/opensemanticsearch/visual_graph_explorer/static/
cp -a src/cytoscape.js-panzoom/cytoscape-panzoom.js ${BUILDDIR}/var/lib/opensemanticsearch/visual_graph_explorer/static/
cp -a src/cytoscape.js-panzoom/cytoscape.js-panzoom.css ${BUILDDIR}/var/lib/opensemanticsearch/visual_graph_explorer/static/
cp -a src/cytoscape.js-panzoom/font-awesome-4.0.3 ${BUILDDIR}/var/lib/opensemanticsearch/visual_graph_explorer/static/
